###############################################################################
##
##  Author: Javier Cervilla.
##  Project: Marketplace en HyperLedger Fabric y Stellarç
##  Date: 22/09/2020
##
###############################################################################
OrdererOrgs:
    - Name: Orderer
      Domain: acme.com
      EnableNodeOUs: true
      Specs:
        - Hostname: orderer
          SANS:
            - localhost
PeerOrgs:
    - Name: Productor
      Domain: productor.acme.com
      EnableNodeOUs: true
      Template:
        Count: 1
        SANS:
          - localhost
      Users:
        Count: 1
    - Name: Consumidor
      Domain: consumidor.acme.com
      EnableNodeOUs: true
      Template:
        Count: 1
        SANS:
          - localhost
      Users:
        Count: 1
    - Name: Mayorista
      Domain: mayorista.acme.com
      EnableNodeOUs: true    
      Template:
        Count: 1
        SANS:
          - localhost
      Users:
        Count: 1